from .context import HookContext
from .manager import HookManager
from .matchers import AndMatcher, AnyMatcher, NameMatcher, PredicateMatcher, TypeMatcher
from .spec import HookSpec, HookType
from .attribution import (
    ActivationLocation,
    AttributionPatchingRunner,
    AttributionResult,
    IntegratedGradientsRunner,
    ModelCall,
    capture_activations,
    capture_activations_and_gradients,
    run_with_patched_activations,
)
from .sr_propagation import (
    EmbeddingPathPoint,
    SRPropagationConfig,
    SRPropagationResult,
    SRPropagationRunner,
    SeparatedPrompt,
    build_embedding_path_points,
    compute_sr_deltas,
    compute_sr_metrics,
    find_subject_token_indices,
    separated_prompt_from_tokenizer,
)
from .transforms import (
    ActivationTransform,
    ComposeTransform,
    NoOpTransform,
    ReplaceTransform,
    ScaleTransform,
    TransformRegistry,
    make_activation_callback,
)

__all__ = [
    "ActivationTransform",
    "ActivationLocation",
    "AndMatcher",
    "AnyMatcher",
    "AttributionPatchingRunner",
    "AttributionResult",
    "ComposeTransform",
    "HookContext",
    "HookManager",
    "HookSpec",
    "HookType",
    "IntegratedGradientsRunner",
    "ModelCall",
    "NameMatcher",
    "NoOpTransform",
    "PredicateMatcher",
    "ReplaceTransform",
    "EmbeddingPathPoint",
    "SRPropagationConfig",
    "SRPropagationResult",
    "SRPropagationRunner",
    "SeparatedPrompt",
    "ScaleTransform",
    "TransformRegistry",
    "TypeMatcher",
    "build_embedding_path_points",
    "capture_activations",
    "capture_activations_and_gradients",
    "compute_sr_deltas",
    "compute_sr_metrics",
    "find_subject_token_indices",
    "make_activation_callback",
    "run_with_patched_activations",
    "separated_prompt_from_tokenizer",
]
